/* eslint-disable */
// @ts-nocheck
// Generated by @meng-xi/vite-plugin. Do not edit.
// 此文件为 @meng-xi/uni-router 提供路由名称和路径的 TypeScript 类型提示
// 当 pages.json 中的页面配置变更时，请同步更新此文件

import '@meng-xi/uni-router'

declare module '@meng-xi/uni-router' {
	interface RouteNameMap {
		pagesIndexIndex: { path: '/pages/index/index'; meta: { title: string; isTab: true } }
		pagesNavigationNavigation: { path: '/pages/navigation/navigation'; meta: { title: string } }
		pagesGuardsGuards: { path: '/pages/guards/guards'; meta: { title: string } }
		pagesDetailDetail: { path: '/pages/detail/detail'; meta: { title: string } }
		pagesProtectedProtected: { path: '/pages/protected/protected'; meta: { title: string; requireAuth: true } }
		pagesLoginLogin: { path: '/pages/login/login'; meta: { title: string } }
		pagesAboutAbout: { path: '/pages/about/about'; meta: { title: string; isTab: true } }
		pagesResolveResolve: { path: '/pages/resolve/resolve'; meta: { title: string } }
		pagesErrorError: { path: '/pages/error/error'; meta: { title: string } }
		pagesSubProfileProfile: { path: '/pages-sub/profile/profile'; meta: { title: string } }
		pagesSubSettingsSettings: { path: '/pages-sub/settings/settings'; meta: { title: string; requireAuth: true } }
	}
}
